//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace Postgree
{
	/// <summary>
	/// Database       : postgres
	/// Data Source    : tcp://localhost:5432
	/// Server Version : 13.3
	/// </summary>
	public partial class PostgresDB : LinqToDB.Data.DataConnection
	{
		public ITable<ParseResult> ParseResults { get { return this.GetTable<ParseResult>(); } }

		partial void InitMappingSchema()
		{
		}

		public PostgresDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PostgresDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PostgresDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PostgresDB(LinqToDbConnectionOptions<PostgresDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="public", Name="parse_results")]
	public partial class ParseResult
	{
		[Column("product_code"),  PrimaryKey(1), NotNull] public double  ProductCode  { get; set; } // double precision
		[Column("name"),          PrimaryKey(2), NotNull] public string  Name         { get; set; } // character varying
		[Column("link_market"),      Nullable           ] public string  LinkMarket   { get; set; } // character varying
		[Column("price"),            Nullable           ] public string  Price        { get; set; } // character varying
		[Column("review_count"),     Nullable           ] public int?    ReviewCount  { get; set; } // integer
		[Column("summary_stars"),    Nullable           ] public double? SummaryStars { get; set; } // double precision
		[Column("category"),         Nullable           ] public string  Category     { get; set; } // character varying
	}

	public static partial class TableExtensions
	{
		public static ParseResult Find(this ITable<ParseResult> table, double ProductCode, string Name)
		{
			return table.FirstOrDefault(t =>
				t.ProductCode == ProductCode &&
				t.Name        == Name);
		}
	}
}

#pragma warning restore 1591
